FROM caddy:builder AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/duckdns@v0.4.0

FROM caddy:alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
