databases:
  - name: postgres
    databaseName: esrog_shuk_db
    user: esrog_shuk_db_user
    ipAllowList: []
    plan: free

services:
  - type: web
    plan: free
    name: rails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
