databases:
  - name: esrog-shuk-v2-api
    databaseName: esrog-shuk-v2-api
    user: esrog-shuk-v2-api

services:
  - type: web
    name: esrog-shuk-v2-api
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: esrog-shuk-v2-api
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
