default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: esrog_shuk_v2_development

test:
  <<: *default
  database: esrog_shuk_v2_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  sslmode: <%= ENV.fetch("DB_SSLMODE") { "require" } %>
